.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. elixir_qt test_elixir_qt
clean: FORCE
	$(MAKE) -C .. elixir_qt_clean test_elixir_qt_clean
check: FORCE
	$(MAKE) -C .. test_elixir_qt_check
elixir-qt elixir-qt.exe: FORCE
	 $(MAKE) -C .. elixir_qt
